In [1]:
import pandas as pd
import numpy as np
import matplotlib as mlp
import matplotlib.pyplot as plt

<img src = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQc4wbsjGqxXgKaaCV79twBaQRhUHkXGURGMg&usqp=CAU" width = 400px, height = 400px >

In [2]:
data = {
    'Input': list(np.arange(1,11)),
    'Output':list(np.arange(2,21 , step = 2))
}
data

{'Input': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 'Output': [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]}

In [3]:
data = pd.DataFrame(data)
data

Input  Output
0      1       2
1      2       4
2      3       6
3      4       8
4      5      10
5      6      12
6      7      14
7      8      16
8      9      18
9     10      20

In [4]:
X,Y = data.Input.values , data.Output.values
print(X)
print(Y)      

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10 12 14 16 18 20]


In [5]:
trainingratio = 80
print('Index of Training ratio : ',int(len(X)*trainingratio/100))

Index of Training ratio :  8


In [6]:
# 80% data for training of X and Y
xtrain = X[:int(len(X)*80/100)]
ytrain = Y[:int(len(Y)*80/100)]

# 20% data for testing of X and Y
xtest = X[int(len(X)*80/100):]
ytest = Y[int(len(Y)*80/100):]

print('Training of X',list(xtrain))
print('Trainig og Y' , list(ytrain))
print('\n')
print('Testing of X', list(xtest))
print('Testing of Y' , list(ytest))

Training of X [1, 2, 3, 4, 5, 6, 7, 8]
Trainig og Y [2, 4, 6, 8, 10, 12, 14, 16]


Testing of X [9, 10]
Testing of Y [18, 20]


# Train and test data distribution with sciketlearn

In [7]:
data.head()

Input  Output
0      1       2
1      2       4
2      3       6
3      4       8
4      5      10

In [8]:
x = data.Input.values
display(x)
y = data.Output.values
display(y)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

## Train test split

In [9]:
from sklearn.model_selection import train_test_split

* shuffled distribution

In [10]:
train_test_split(x,y,test_size = 0.3)

[array([ 3,  5,  2,  1,  4, 10,  7]),
 array([8, 9, 6]),
 array([ 6, 10,  4,  2,  8, 20, 14]),
 array([16, 18, 12])]

* Unshuffled distribution

In [11]:
train_test_split(x,y , test_size = 0.3 ,shuffle=False)

[array([1, 2, 3, 4, 5, 6, 7]),
 array([ 8,  9, 10]),
 array([ 2,  4,  6,  8, 10, 12, 14]),
 array([16, 18, 20])]

In [12]:
xtrain , xtest , ytrain , ytest = train_test_split(x,y, test_size = 0.3)
display(xtrain)
display(xtest)
display(ytrain)
display(ytest)

array([5, 6, 1, 9, 2, 3, 4])

array([ 8, 10,  7])

array([10, 12,  2, 18,  4,  6,  8])

array([16, 20, 14])